name: Build on commit

on:
  push:
    branches: [ '**', '!release/*' ]
  pull_request:
    branches: [ '**', '!release/*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build for Linux (x64)
        run: GOOS=linux GOARCH=amd64 go build -o bin\hueshelly-linux .
      - name: Build for Raspberry
        run: env GOOS=linux GOARCH=arm GOARM=5 go build -o bin\hueshelly-raspberry .
      - name: Build for macOS
        run: env GOOS=darwin GOARCH=amd64 go build -o bin\hueshelly-macos .
      - name: Build for macOS (Apple Silicon)
        run: env GOOS=darwin GOARCH=amd64 go build -o bin\hueshelly-macos-apple-silicon .
      - name: Build for Windows (x64)
        run: GOOS=windows GOARCH=amd64 go build -o bin\hueshelly-win64.exe .
      - run: echo $(pwd)
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: go-binaries
          path: bin/*
          #          path: /home/runner/work/hueshelly/hueshelly/bin/*
          if-no-files-found: error


